### ISSUE TITLE
Profile backend support (register, login, forgot password APIs)

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-server#63]

**Comment by wolffan** [comment]
➤ Ben Baron commented:

https://trello.com/c/KiRpKpWx/21-70-user-profile-ui

**Comment by wolffan** [comment]
➤ Ben Baron commented:

Some notes:

  1. Enforce password length client side (as server never sees password, only a hash)
  2. Minimum password length of 16 characters, no maximum length
  3. All unicode and ASCII chars supported
  4. Check passwords client side against a list of known bad passwords as best as possible without shipping gigabytes of bad password lists (potentially run a secure web service where we send some kind of password hash and check against known leaked passwords--need to discuss with Jin)

Great info on good password requirements here: https://nakedsecurity.sophos.com/2016/08/18/nists-new-password-rules-what-you-need-to-know/

**Comment by einsteinx2** [comment]
➤ Christopher Downer commented:

Should you wish to assign usernames to users, this is a great resource - https://gist.github.com/caseyohara/1453705#file-reserved_usernames-rb-L10

**Comment by einsteinx2** [comment]
issue moved to balance-open repo
