### ISSUE TITLE
Move servers to europe for legal purposes

### ISSUE THREAD

**Issue by wolffan** [balancemymoney/balance-server#79]

**Comment by wolffan** [comment]
➤ Ben Baron commented:

Looks like GAE doesn't support migrating to new regions so I'll have to create a new project there and push to it. Will require some downtime, which isn't a bit issue since we're in beta and only affects coinbase accounts anyway. When we get ready to push the profile code, we can push it to the new location.

**Comment by einsteinx2** [comment]
issue moved to balance-open repo
